### ISSUE TITLE
can this run in a php project ?

### ISSUE THREAD

**Issue by oceatoon** [Oagenda/react-timings-picker#1]
hi 
it's a nice tool 
can it run in a php project ?

**Comment by TBAPI-0KA** [comment]
Hi Tibor,

Yes, you can run it in a PHP project. It's completely front-end component, implemented on React, and it's back-end agnostic. While the most essential is to use Node with Browserify, you can build a component (or use 'lib' folder inside repository root and Require) and use it in your application.
